"""
Terms & Conditions / Disclaimer dialog.

Shown once at startup. User must scroll to bottom and tick the checkbox
before the main app is allowed to open.
"""
import customtkinter as ctk
from ui.theme import (
    BG_DARK, BG_CARD, BG_INPUT, BORDER, ACCENT, RED, YELLOW, GREEN,
    TEXT_PRIMARY, TEXT_SECONDARY, FONT_TITLE, FONT_BODY, FONT_SMALL, CORNER_RADIUS,
)

TERMS_TEXT = """\
BEST BRAND CORP TRADING & PREDICTION BOT
SOFTWARE TERMS OF USE, RISK DISCLOSURE & LIABILITY DISCLAIMER
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Last updated: June 21, 2026

PLEASE READ THESE TERMS CAREFULLY BEFORE USING THIS SOFTWARE.
BY CLICKING "I AGREE AND CONTINUE" YOU CONFIRM THAT YOU HAVE
READ, UNDERSTOOD, AND AGREED TO EVERY PROVISION BELOW.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1.  ACCEPTANCE OF TERMS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This software ("the Software") is provided by Best Brand Corp
and its creator(s) ("the Creator"). By installing, copying, or
using the Software in any manner you agree to be bound by these
Terms. If you do not agree, do not use the Software.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2.  NO FINANCIAL OR INVESTMENT ADVICE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The Software is a TECHNICAL TOOL ONLY. Nothing it generates,
displays, signals, or executes constitutes financial advice,
investment advice, tax advice, legal advice, or any other form
of professional advice. The Creator is not a registered
investment adviser, broker-dealer, financial planner, or
licensed financial professional in any jurisdiction.

All trading signals, market analysis, probability estimates,
suggested actions, take-profit levels, and stop-loss levels
generated by the Software are ALGORITHMIC OUTPUTS FOR
INFORMATIONAL PURPOSES ONLY. They are not recommendations to
buy, sell, or hold any asset.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
3.  RISK WARNING — TRADING IS EXTREMELY RISKY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

TRADING CRYPTOCURRENCIES, PERPETUAL FUTURES, AND PREDICTION
MARKET CONTRACTS CARRIES AN EXTREMELY HIGH LEVEL OF RISK AND
MAY NOT BE SUITABLE FOR ALL INVESTORS OR USERS.

You acknowledge and accept that:

  (a) You may lose ALL of the capital you invest or more,
      including through liquidation of leveraged positions.

  (b) Past performance of any signal, strategy, or indicator
      is NOT indicative of future results.

  (c) Automated trading systems can malfunction, produce
      erroneous orders, or fail to execute orders at intended
      prices due to software bugs, network failures, exchange
      outages, API changes, or market conditions.

  (d) Leverage amplifies both gains AND losses. Using high
      leverage can result in losses exceeding your initial
      deposit.

  (e) Prediction markets (Polymarket, Kalshi, Metaculus) involve
      speculative wagering. You may lose your entire stake.

  (f) Cryptocurrency and decentralised exchange (DEX) transactions
      are irreversible once confirmed on-chain. Errors cannot
      be undone.

  (g) Smart contract vulnerabilities, exchange hacks, liquidity
      crises, and regulatory actions may result in total loss
      of funds without recourse.

  (h) Tax obligations from trading activities are entirely
      your responsibility. The Software does not provide tax
      reporting or tax advice.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
4.  LIMITATION OF LIABILITY — COMPLETE EXCLUSION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:

THE CREATOR, BEST BRAND CORP, ITS AFFILIATES, OFFICERS,
EMPLOYEES, AGENTS, CONTRIBUTORS, AND LICENSORS SHALL NOT BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES WHATSOEVER,
INCLUDING BUT NOT LIMITED TO:

  • Loss of profits, revenue, capital, or savings
  • Loss of cryptocurrency, tokens, or digital assets
  • Trading losses of any amount on any exchange or platform
  • Losses arising from automated or manual trade execution
  • Losses from prediction market positions
  • Costs of substitute goods or services
  • Business interruption losses
  • Loss of data or corruption of data
  • Losses arising from software bugs, errors, or inaccuracies
  • Losses from third-party service failures (exchanges, APIs,
    RPC nodes, internet connectivity)

ARISING OUT OF OR RELATED TO YOUR USE OF, OR INABILITY TO USE,
THE SOFTWARE, EVEN IF THE CREATOR HAS BEEN ADVISED OF THE
POSSIBILITY OF SUCH DAMAGES.

IN JURISDICTIONS THAT DO NOT ALLOW THE EXCLUSION OR LIMITATION
OF CERTAIN DAMAGES, THE CREATOR'S LIABILITY SHALL BE LIMITED TO
THE MAXIMUM EXTENT PERMITTED BY LAW, WHICH IN ALL CASES SHALL
NOT EXCEED ZERO DOLLARS ($0.00 USD).

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
5.  YOUR SOLE RESPONSIBILITY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

You are solely responsible for:

  (a) All trading decisions, whether made manually or through
      enabling the auto-trade / auto-bet features.

  (b) Securing your private keys, API credentials, and .env
      configuration file. The Creator assumes no liability for
      unauthorised access to your wallet or accounts.

  (c) Ensuring the Software's use complies with all applicable
      laws, regulations, and platform terms of service in your
      jurisdiction, including but not limited to securities laws,
      commodities laws, and gambling regulations.

  (d) Conducting your own due diligence and risk assessment
      before committing any funds.

  (e) Monitoring all open positions, orders, and bets at all
      times. Automated systems should never be left completely
      unattended.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
6.  NO WARRANTY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

THE SOFTWARE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT
WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.

THE CREATOR DOES NOT WARRANT THAT:
  • The Software will be error-free or uninterrupted
  • Signals or analysis will be accurate or profitable
  • The Software will be compatible with all exchanges,
    wallets, or platforms at all times

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
7.  INDEMNIFICATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

You agree to indemnify, defend, and hold harmless the Creator
and Best Brand Corp from and against any and all claims,
damages, losses, costs, and expenses (including reasonable
legal fees) arising from: (a) your use of the Software;
(b) your violation of these Terms; (c) your violation of any
third-party rights or applicable law.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
8.  THIRD-PARTY SERVICES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The Software integrates with third-party services including
Hyperliquid, Polymarket, Kalshi, Metaculus, TradingView,
Telegram, and various RPC providers. The Creator is not
affiliated with these services and accepts no liability for
their availability, accuracy, terms, or actions.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
9.  GOVERNING LAW & DISPUTE RESOLUTION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

These Terms shall be governed by the laws of the jurisdiction
of the Creator's domicile, without regard to conflict-of-law
principles. Any disputes shall be resolved by binding
arbitration on an individual basis. You waive any right to
participate in class-action proceedings.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
10. AMENDMENT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The Creator reserves the right to modify these Terms at any
time. Continued use of the Software following any update
constitutes acceptance of the revised Terms.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
11. ENTIRE AGREEMENT & SEVERABILITY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

These Terms constitute the entire agreement between you and
the Creator regarding use of the Software and supersede all
prior agreements. If any provision is found unenforceable,
the remaining provisions remain in full force.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

BY CHECKING THE BOX BELOW AND CLICKING "I AGREE AND CONTINUE"
YOU CONFIRM THAT YOU:

  ✓ Are at least 18 years of age (or the legal adult age in
    your jurisdiction, whichever is higher).
  ✓ Have read and understood all provisions of these Terms.
  ✓ Accept full and sole responsibility for all trading and
    betting decisions made with this Software.
  ✓ Understand and accept the complete risk of financial loss.
  ✓ Release the Creator from all present and future liability
    arising from your use of this Software.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
© 2026 Best Brand Corp. All rights reserved.
"""


class TermsDialog(ctk.CTkToplevel):
    """
    Modal Terms & Conditions window.

    Blocks the main window until the user scrolls to the bottom,
    checks the agreement box, and clicks "I Agree".
    Returns True if accepted, False if declined/closed.
    """

    def __init__(self, parent):
        super().__init__(parent)
        self.title("Terms of Use & Risk Disclaimer — Best Brand Corp")
        self.geometry("780x640")
        self.resizable(False, False)
        self.configure(fg_color=BG_DARK)
        self.grab_set()   # modal
        self.lift()
        self.focus_force()

        self.accepted = False
        self._scrolled_to_bottom = False

        self._build()
        self.protocol("WM_DELETE_WINDOW", self._on_close)

    def _build(self):
        # Header
        header = ctk.CTkFrame(self, fg_color=BG_CARD, corner_radius=0)
        header.pack(fill="x")

        ctk.CTkLabel(
            header,
            text="⚠  Terms of Use & Risk Disclaimer",
            font=("Inter", 16, "bold"),
            text_color=YELLOW,
        ).pack(side="left", padx=20, pady=14)

        ctk.CTkLabel(
            header,
            text="Best Brand Corp",
            font=FONT_SMALL,
            text_color=TEXT_SECONDARY,
        ).pack(side="right", padx=20)

        # Subtitle warning
        ctk.CTkLabel(
            self,
            text="Scroll to the bottom, read all terms, then check the box to continue.",
            font=FONT_SMALL,
            text_color=TEXT_SECONDARY,
        ).pack(pady=(10, 4))

        # Text area
        self.textbox = ctk.CTkTextbox(
            self,
            fg_color=BG_INPUT,
            text_color=TEXT_PRIMARY,
            font=("Courier New", 11),
            corner_radius=CORNER_RADIUS,
            border_width=1,
            border_color=BORDER,
            wrap="word",
            state="normal",
        )
        self.textbox.pack(fill="both", expand=True, padx=20, pady=(0, 8))
        self.textbox.insert("1.0", TERMS_TEXT)
        self.textbox.configure(state="disabled")

        # Detect scroll-to-bottom
        self.textbox._textbox.bind("<KeyRelease>", self._on_scroll)
        self.textbox._textbox.bind("<ButtonRelease>", self._on_scroll)
        self.textbox._textbox.bind("<MouseWheel>", self._on_scroll)
        self.textbox._textbox.bind("<Button-4>", self._on_scroll)  # Linux scroll up
        self.textbox._textbox.bind("<Button-5>", self._on_scroll)  # Linux scroll down

        # Scroll hint label
        self.scroll_hint = ctk.CTkLabel(
            self,
            text="↓  Scroll down to read all terms before you can agree",
            font=FONT_SMALL,
            text_color=YELLOW,
        )
        self.scroll_hint.pack(pady=(0, 4))

        # Checkbox row
        self.agree_var = ctk.BooleanVar(value=False)
        self.checkbox = ctk.CTkCheckBox(
            self,
            text=(
                "I have read, understood, and agree to all Terms of Use and Risk Disclosures.\n"
                "I accept full responsibility for all trading decisions and financial losses."
            ),
            variable=self.agree_var,
            checkbox_width=20,
            checkbox_height=20,
            checkmark_color=BG_DARK,
            fg_color=GREEN,
            border_color=BORDER,
            text_color=TEXT_PRIMARY,
            font=FONT_SMALL,
            state="disabled",   # enabled after scroll-to-bottom
            command=self._on_checkbox,
        )
        self.checkbox.pack(padx=20, pady=(4, 8), anchor="w")

        # Buttons
        btn_row = ctk.CTkFrame(self, fg_color="transparent")
        btn_row.pack(fill="x", padx=20, pady=(0, 16))

        ctk.CTkButton(
            btn_row,
            text="✕  Decline & Exit",
            fg_color=BG_INPUT,
            text_color=RED,
            hover_color=BORDER,
            font=FONT_BODY,
            command=self._on_close,
        ).pack(side="left")

        self.agree_btn = ctk.CTkButton(
            btn_row,
            text="✓  I Agree & Continue",
            fg_color=BORDER,           # greyed out until checked
            text_color=TEXT_MUTED,
            font=("Inter", 13, "bold"),
            state="disabled",
            command=self._on_agree,
        )
        self.agree_btn.pack(side="right")

    def _on_scroll(self, event=None):
        if self._scrolled_to_bottom:
            return
        try:
            # yview returns (top_fraction, bottom_fraction)
            _, bottom = self.textbox._textbox.yview()
            if bottom >= 0.98:
                self._scrolled_to_bottom = True
                self.checkbox.configure(state="normal")
                self.scroll_hint.configure(
                    text="✓  You've reached the bottom. Check the box below to continue.",
                    text_color=GREEN,
                )
        except Exception:
            pass

    def _on_checkbox(self):
        if self.agree_var.get():
            self.agree_btn.configure(
                state="normal",
                fg_color=GREEN,
                text_color="black",
            )
        else:
            self.agree_btn.configure(
                state="disabled",
                fg_color=BORDER,
                text_color=TEXT_MUTED,
            )

    def _on_agree(self):
        self.accepted = True
        self.grab_release()
        self.destroy()

    def _on_close(self):
        self.accepted = False
        self.grab_release()
        self.destroy()
