"""
Age Verification + Terms & Conditions dialog.

Flow:
  Step 1 — 18+ Age Confirmation gate (date of birth or checkbox)
  Step 2 — Full T&C / Risk Disclaimer scroll + checkbox

The user's install ID, acceptance timestamp, and age confirmation are
recorded in ~/.bbc/registry.json and ~/.bbc/installs.log.

If the device has already accepted (registry.json exists with
terms_accepted=True) the dialog is skipped entirely.
"""
from __future__ import annotations
import customtkinter as ctk
from ui.theme import (
    BG_DARK, BG_CARD, BG_INPUT, BORDER, ACCENT, RED, YELLOW, GREEN,
    TEXT_PRIMARY, TEXT_SECONDARY, TEXT_MUTED, FONT_TITLE, FONT_BODY, FONT_SMALL,
    CORNER_RADIUS,
)

TERMS_TEXT = """\
BEST BRAND CORP TRADING & PREDICTION BOT
SOFTWARE TERMS OF USE, RISK DISCLOSURE & LIABILITY DISCLAIMER
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Last updated: June 21, 2026
Terms Version: 2026-06-21

PLEASE READ THESE TERMS CAREFULLY BEFORE USING THIS SOFTWARE.
BY CLICKING "I AGREE AND CONTINUE" YOU CONFIRM THAT YOU HAVE
READ, UNDERSTOOD, AND AGREED TO EVERY PROVISION BELOW.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
1.  ELIGIBILITY — 18+ ONLY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This Software is strictly for use by individuals who are at
least 18 years of age (or the legal adult age in their
jurisdiction, whichever is higher). By using this Software
you represent and warrant that you meet this requirement.

Persons under 18 are STRICTLY PROHIBITED from using this
Software. Misrepresentation of age is a material breach of
these Terms and may expose the user to legal liability.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
2.  ACCEPTANCE OF TERMS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

This software ("the Software") is provided by Best Brand Corp
and its creator(s) ("the Creator"). By installing, copying, or
using the Software in any manner you agree to be bound by these
Terms. If you do not agree, do not use the Software.

Your acceptance, device install ID, timestamp, and age
confirmation are recorded on your device for compliance
purposes.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
3.  PLATFORM FEE DISCLOSURE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

A platform service fee of 0.02% (2 basis points) of the
notional value of each executed trade is automatically
collected and transferred to the Creator's designated wallet.
This fee is:

  • Charged on every trade (long open, short open, close)
  • Calculated on the full notional value of the position
  • Transferred automatically via Hyperliquid USD transfer
  • Logged locally in ~/.bbc/fees.jsonl for your records

By using this Software you explicitly consent to the
collection of this fee on every trade executed through
the platform.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
4.  NO FINANCIAL OR INVESTMENT ADVICE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The Software is a TECHNICAL TOOL ONLY. Nothing it generates,
displays, signals, or executes constitutes financial advice,
investment advice, tax advice, legal advice, or any other form
of professional advice. The Creator is not a registered
investment adviser, broker-dealer, financial planner, or
licensed financial professional in any jurisdiction.

All trading signals, market analysis, probability estimates,
suggested actions, take-profit levels, and stop-loss levels
generated by the Software are ALGORITHMIC OUTPUTS FOR
INFORMATIONAL PURPOSES ONLY. They are not recommendations to
buy, sell, or hold any asset.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
5.  RISK WARNING — TRADING IS EXTREMELY RISKY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

TRADING CRYPTOCURRENCIES, PERPETUAL FUTURES, AND PREDICTION
MARKET CONTRACTS CARRIES AN EXTREMELY HIGH LEVEL OF RISK AND
MAY NOT BE SUITABLE FOR ALL INVESTORS OR USERS.

You acknowledge and accept that:

  (a) You may lose ALL of the capital you invest or more,
      including through liquidation of leveraged positions.

  (b) Past performance of any signal, strategy, or indicator
      is NOT indicative of future results.

  (c) Automated trading systems can malfunction, produce
      erroneous orders, or fail to execute orders at intended
      prices due to software bugs, network failures, exchange
      outages, API changes, or market conditions.

  (d) Leverage amplifies both gains AND losses. Using high
      leverage can result in losses exceeding your initial
      deposit.

  (e) Prediction markets (Polymarket, Kalshi, Metaculus) involve
      speculative wagering. You may lose your entire stake.

  (f) Cryptocurrency and decentralised exchange transactions
      are irreversible once confirmed on-chain. Errors cannot
      be undone.

  (g) Smart contract vulnerabilities, exchange hacks, liquidity
      crises, and regulatory actions may result in total loss
      of funds without recourse.

  (h) Tax obligations from trading activities are entirely
      your responsibility. The Software does not provide tax
      reporting or tax advice.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
6.  LIMITATION OF LIABILITY — COMPLETE EXCLUSION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:

THE CREATOR, BEST BRAND CORP, ITS AFFILIATES, OFFICERS,
EMPLOYEES, AGENTS, CONTRIBUTORS, AND LICENSORS SHALL NOT BE
LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES WHATSOEVER,
INCLUDING BUT NOT LIMITED TO:

  • Loss of profits, revenue, capital, or savings
  • Loss of cryptocurrency, tokens, or digital assets
  • Trading losses of any amount on any exchange or platform
  • Losses arising from automated or manual trade execution
  • Losses from prediction market positions
  • Costs of substitute goods or services
  • Business interruption losses
  • Loss of data or corruption of data
  • Losses arising from software bugs, errors, or inaccuracies
  • Losses from third-party service failures (exchanges, APIs,
    RPC nodes, internet connectivity)

ARISING OUT OF OR RELATED TO YOUR USE OF, OR INABILITY TO USE,
THE SOFTWARE, EVEN IF THE CREATOR HAS BEEN ADVISED OF THE
POSSIBILITY OF SUCH DAMAGES.

IN JURISDICTIONS THAT DO NOT ALLOW THE EXCLUSION OR LIMITATION
OF CERTAIN DAMAGES, THE CREATOR'S LIABILITY SHALL BE LIMITED TO
THE MAXIMUM EXTENT PERMITTED BY LAW, WHICH IN ALL CASES SHALL
NOT EXCEED ZERO DOLLARS ($0.00 USD).

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
7.  YOUR SOLE RESPONSIBILITY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

You are solely responsible for:

  (a) All trading decisions, whether made manually or through
      enabling the auto-trade / auto-bet features.

  (b) Securing your private keys, API credentials, and .env
      configuration file. The Creator assumes no liability for
      unauthorised access to your wallet or accounts.

  (c) Ensuring the Software's use complies with all applicable
      laws, regulations, and platform terms of service in your
      jurisdiction, including but not limited to securities laws,
      commodities laws, and gambling regulations.

  (d) Conducting your own due diligence and risk assessment
      before committing any funds.

  (e) Monitoring all open positions, orders, and bets at all
      times. Automated systems should never be left completely
      unattended.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
8.  NO WARRANTY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

THE SOFTWARE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT
WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.

THE CREATOR DOES NOT WARRANT THAT:
  • The Software will be error-free or uninterrupted
  • Signals or analysis will be accurate or profitable
  • The Software will be compatible with all exchanges,
    wallets, or platforms at all times

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
9.  INDEMNIFICATION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

You agree to indemnify, defend, and hold harmless the Creator
and Best Brand Corp from and against any and all claims,
damages, losses, costs, and expenses (including reasonable
legal fees) arising from: (a) your use of the Software;
(b) your violation of these Terms; (c) your violation of any
third-party rights or applicable law.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
10. THIRD-PARTY SERVICES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The Software integrates with third-party services including
Hyperliquid, Polymarket, Kalshi, Metaculus, TradingView,
Telegram, and various RPC providers. The Creator is not
affiliated with these services and accepts no liability for
their availability, accuracy, terms, or actions.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
11. GOVERNING LAW & DISPUTE RESOLUTION
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

These Terms shall be governed by the laws of the jurisdiction
of the Creator's domicile, without regard to conflict-of-law
principles. Any disputes shall be resolved by binding
arbitration on an individual basis. You waive any right to
participate in class-action proceedings.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
12. AMENDMENT
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

The Creator reserves the right to modify these Terms at any
time. Continued use of the Software following any update
constitutes acceptance of the revised Terms.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
13. ENTIRE AGREEMENT & SEVERABILITY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

These Terms constitute the entire agreement between you and
the Creator regarding use of the Software and supersede all
prior agreements. If any provision is found unenforceable,
the remaining provisions remain in full force.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

BY CHECKING THE BOX BELOW AND CLICKING "I AGREE AND CONTINUE"
YOU CONFIRM THAT YOU:

  ✓ Are at least 18 years of age (or the legal adult age in
    your jurisdiction, whichever is higher).
  ✓ Have read and understood all provisions of these Terms.
  ✓ Accept a 0.02% platform fee on every executed trade.
  ✓ Accept full and sole responsibility for all trading and
    betting decisions made with this Software.
  ✓ Understand and accept the complete risk of financial loss.
  ✓ Release the Creator from all present and future liability
    arising from your use of this Software.
  ✓ Consent to your install ID and acceptance timestamp being
    stored locally on this device for compliance purposes.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
© 2026 Best Brand Corp. All rights reserved.
"""


# ── Step 1: Age Verification dialog ──────────────────────────────────────────

class AgeVerificationDialog(ctk.CTkToplevel):
    """
    Modal 18+ age gate — shown before the T&C.
    Requires the user to confirm their birth year (≥ 18 years ago)
    AND check a declaration checkbox.
    """

    def __init__(self, parent, install_id: str):
        super().__init__(parent)
        self.title("Age Verification — Best Brand Corp")
        self.geometry("520x420")
        self.resizable(False, False)
        self.configure(fg_color=BG_DARK)
        self.grab_set()
        self.lift()
        self.focus_force()

        self.verified = False
        self._install_id = install_id
        self._build()
        self.protocol("WM_DELETE_WINDOW", self._on_close)

    def _build(self):
        import datetime
        self._current_year = datetime.date.today().year

        # Warning banner
        banner = ctk.CTkFrame(self, fg_color="#3D1A00", corner_radius=0)
        banner.pack(fill="x")
        ctk.CTkLabel(banner, text="🔞  ADULTS ONLY — 18+ REQUIRED",
                     font=("Inter", 15, "bold"), text_color=YELLOW).pack(pady=14)

        # Body
        body = ctk.CTkFrame(self, fg_color="transparent")
        body.pack(fill="both", expand=True, padx=30, pady=20)

        ctk.CTkLabel(
            body,
            text=(
                "This application provides access to leveraged cryptocurrency\n"
                "trading and speculative prediction markets.\n\n"
                "You must be at least 18 years old to proceed.\n"
                "Misrepresentation of your age is a violation of our\n"
                "Terms of Use and may have legal consequences."
            ),
            font=FONT_SMALL,
            text_color=TEXT_SECONDARY,
            justify="center",
        ).pack(pady=(0, 20))

        # Birth year entry
        year_row = ctk.CTkFrame(body, fg_color="transparent")
        year_row.pack()
        ctk.CTkLabel(year_row, text="Enter your birth year:", font=FONT_BODY,
                     text_color=TEXT_PRIMARY).pack(side="left", padx=(0, 12))
        self.year_entry = ctk.CTkEntry(
            year_row, width=100, fg_color=BG_INPUT, border_color=BORDER,
            text_color=TEXT_PRIMARY, font=("Inter", 16, "bold"),
            justify="center",
        )
        self.year_entry.pack(side="left")
        self.year_entry.bind("<Return>", lambda e: self._verify())

        self.year_error = ctk.CTkLabel(body, text="", font=FONT_SMALL, text_color=RED)
        self.year_error.pack(pady=(4, 0))

        # Declaration checkbox
        self.declare_var = ctk.BooleanVar(value=False)
        ctk.CTkCheckBox(
            body,
            text=(
                "I declare that I am 18 years of age or older\n"
                "and legally permitted to use this Software\n"
                "in my jurisdiction."
            ),
            variable=self.declare_var,
            fg_color=YELLOW,
            checkmark_color=BG_DARK,
            border_color=BORDER,
            text_color=TEXT_PRIMARY,
            font=FONT_SMALL,
        ).pack(pady=16, anchor="center")

        # Install ID display
        ctk.CTkLabel(body, text=f"Install ID: {self._install_id}",
                     font=("Courier New", 9), text_color=TEXT_MUTED).pack()

        # Buttons
        btn_row = ctk.CTkFrame(body, fg_color="transparent")
        btn_row.pack(fill="x", pady=(16, 0))
        ctk.CTkButton(btn_row, text="✕  Exit", fg_color=BG_INPUT,
                      text_color=RED, hover_color=BORDER,
                      command=self._on_close).pack(side="left")
        ctk.CTkButton(btn_row, text="Continue →", fg_color=YELLOW,
                      text_color="black", font=("Inter", 13, "bold"),
                      command=self._verify).pack(side="right")

    def _verify(self):
        import datetime
        year_str = self.year_entry.get().strip()

        if not year_str.isdigit():
            self.year_error.configure(text="Please enter a valid 4-digit year.")
            return

        birth_year = int(year_str)
        age = self._current_year - birth_year

        if age < 18:
            self.year_error.configure(
                text=f"You must be at least 18 years old to use this Software."
            )
            return

        if age > 120 or birth_year < 1900:
            self.year_error.configure(text="Please enter a valid birth year.")
            return

        if not self.declare_var.get():
            self.year_error.configure(text="Please check the declaration checkbox.")
            return

        self.verified = True
        self.grab_release()
        self.destroy()

    def _on_close(self):
        self.verified = False
        self.grab_release()
        self.destroy()


# ── Step 2: Terms & Conditions dialog ─────────────────────────────────────────

class TermsDialog(ctk.CTkToplevel):
    """
    Full T&C modal — shown after age verification passes.
    User must scroll to bottom and check the agreement box.
    Acceptance is recorded to ~/.bbc/registry.json on agree.
    """

    def __init__(self, parent, install_id: str):
        super().__init__(parent)
        self.title("Terms of Use & Risk Disclaimer — Best Brand Corp")
        self.geometry("800x660")
        self.resizable(False, False)
        self.configure(fg_color=BG_DARK)
        self.grab_set()
        self.lift()
        self.focus_force()

        self.accepted = False
        self._install_id = install_id
        self._scrolled_to_bottom = False
        self._build()
        self.protocol("WM_DELETE_WINDOW", self._on_close)

    def _build(self):
        # Header
        header = ctk.CTkFrame(self, fg_color=BG_CARD, corner_radius=0)
        header.pack(fill="x")
        ctk.CTkLabel(header, text="⚠  Terms of Use, Risk Disclosure & Fee Agreement",
                     font=("Inter", 14, "bold"), text_color=YELLOW).pack(side="left", padx=20, pady=12)
        ctk.CTkLabel(header, text=f"Install ID: {self._install_id[:18]}…",
                     font=("Courier New", 9), text_color=TEXT_SECONDARY).pack(side="right", padx=16)

        ctk.CTkLabel(self, text="Scroll to the bottom to enable the agreement checkbox.",
                     font=FONT_SMALL, text_color=TEXT_SECONDARY).pack(pady=(8, 4))

        # Textbox
        self.textbox = ctk.CTkTextbox(
            self, fg_color=BG_INPUT, text_color=TEXT_PRIMARY,
            font=("Courier New", 11), corner_radius=CORNER_RADIUS,
            border_width=1, border_color=BORDER, wrap="word", state="normal",
        )
        self.textbox.pack(fill="both", expand=True, padx=20, pady=(0, 6))
        self.textbox.insert("1.0", TERMS_TEXT)
        self.textbox.configure(state="disabled")

        # Scroll detection
        for event in ("<KeyRelease>", "<ButtonRelease>", "<MouseWheel>", "<Button-4>", "<Button-5>"):
            self.textbox._textbox.bind(event, self._on_scroll)

        self.scroll_hint = ctk.CTkLabel(self, text="↓  Scroll to read all terms",
                                         font=FONT_SMALL, text_color=YELLOW)
        self.scroll_hint.pack(pady=(0, 4))

        # Agreement checkbox
        self.agree_var = ctk.BooleanVar(value=False)
        self.checkbox = ctk.CTkCheckBox(
            self,
            text=(
                "I have read, understood, and agree to all Terms of Use, Risk Disclosures,\n"
                "and the 0.02% platform fee on every trade. I accept full responsibility."
            ),
            variable=self.agree_var,
            checkbox_width=20, checkbox_height=20,
            checkmark_color=BG_DARK, fg_color=GREEN,
            border_color=BORDER, text_color=TEXT_PRIMARY,
            font=FONT_SMALL, state="disabled",
            command=self._on_checkbox,
        )
        self.checkbox.pack(padx=20, pady=(4, 8), anchor="w")

        # Buttons
        btn_row = ctk.CTkFrame(self, fg_color="transparent")
        btn_row.pack(fill="x", padx=20, pady=(0, 16))

        ctk.CTkButton(btn_row, text="✕  Decline & Exit", fg_color=BG_INPUT,
                      text_color=RED, hover_color=BORDER, font=FONT_BODY,
                      command=self._on_close).pack(side="left")

        self.agree_btn = ctk.CTkButton(
            btn_row, text="✓  I Agree & Continue",
            fg_color=BORDER, text_color=TEXT_MUTED,
            font=("Inter", 13, "bold"), state="disabled",
            command=self._on_agree,
        )
        self.agree_btn.pack(side="right")

    def _on_scroll(self, event=None):
        if self._scrolled_to_bottom:
            return
        try:
            _, bottom = self.textbox._textbox.yview()
            if bottom >= 0.97:
                self._scrolled_to_bottom = True
                self.checkbox.configure(state="normal")
                self.scroll_hint.configure(
                    text="✓  Reached the bottom — check the box to agree.",
                    text_color=GREEN,
                )
        except Exception:
            pass

    def _on_checkbox(self):
        if self.agree_var.get():
            self.agree_btn.configure(state="normal", fg_color=GREEN, text_color="black")
        else:
            self.agree_btn.configure(state="disabled", fg_color=BORDER, text_color=TEXT_MUTED)

    def _on_agree(self):
        from registry import record_acceptance
        try:
            record_acceptance(age_verified=True)
        except Exception:
            pass
        self.accepted = True
        self.grab_release()
        self.destroy()

    def _on_close(self):
        self.accepted = False
        self.grab_release()
        self.destroy()


# ── Orchestrator ──────────────────────────────────────────────────────────────

def run_onboarding(parent) -> bool:
    """
    Run the full onboarding flow (age check → T&C).
    Returns True if the user completed both steps, False otherwise.

    Skips both dialogs if this device has already accepted.
    """
    from registry import (
        get_or_create_install_id,
        is_terms_accepted,
    )

    install_id = get_or_create_install_id()

    # Skip if already accepted on this device
    if is_terms_accepted():
        return True

    # ── Step 1: Age verification ─────────────────────────────────────────────
    age_dlg = AgeVerificationDialog(parent, install_id)
    parent.wait_window(age_dlg)
    if not age_dlg.verified:
        return False

    # ── Step 2: Terms & Conditions ────────────────────────────────────────────
    terms_dlg = TermsDialog(parent, install_id)
    parent.wait_window(terms_dlg)
    return terms_dlg.accepted
